name: MmdSkin
version: 1.0.0
main: com.opdent.mmdskin.bukkit.MmdSkinBukkit
api-version: 1.21
authors: [shiroha, Trae]
description: MC-MMD-rust Bukkit port for syncing player models.
website: https://github.com/shiroha/MC-MMD-rust
